### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by rrrix** [GongT/flat-yarn-install#2]
Hey @GongT,

I saw your post for `yarn install --flat` ([yarn#1658](https://github.com/yarnpkg/yarn/issues/1658#issuecomment-541019394)) which led me to this tool.

I tried it (`yarn global add @gongt/flat-yarn-install`) and on first execution, I get:

```javascript
$ flat-yarn-install --newest
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module '@idlebox/node-json-edit'
Require stack:
- /Users/me/.config/yarn/global/node_modules/@gongt/flat-yarn-install/lib/index.js
- /Users/me/.config/yarn/global/node_modules/@gongt/flat-yarn-install/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/me/.config/yarn/global/node_modules/@gongt/flat-yarn-install/lib/index.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/me/.config/yarn/global/node_modules/@gongt/flat-yarn-install/lib/index.js',
    '/Users/me/.config/yarn/global/node_modules/@gongt/flat-yarn-install/bin.js'
  ]
}
```

I tried cloning your git repo too, but `yarn install` on that one gave me an SSL error:

```javascript
~/git/GongT/flat-yarn-install $ yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://mirror.service.gongt.me:59443/npm/@idlebox/node-json-edit/-/node-json-edit-1.0.16.tgz: self signed certificate".
info If you think this is a bug, please open a bug report with the information provided in "/Users/me/dev/git/GongT/flat-yarn-install/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

No idea if there's a way to fix that last one - looks like your own NPM server or something. Anyways, very interested to see this thing work. Thanks in advance!

**Comment by GongT** [comment]
Too long no maintains.😥

`1.0.2` published. you can try it again.
